[package]
name = "i-hom/echoframework"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@0.1.2"

[server-dependencies]
Cmdr = "evaera/cmdr@1.8.4"