[package]
name = "i-hom/echoframework"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@0.1.2"
Promise = "evaera/promise@3.2.1"
Component = "sleitnick/component@2.3.0"

[server-dependencies]