[package]
name = "i-hom/echoframework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
Flipper = "reselim/flipper@2.0.0"
RoactFlipper = "reselim/roact-flipper@1.1.0"
Trove = "sleitnick/trove@0.1.3"
Component = "sleitnick/component@2.0.0"

[server-dependencies]
Cmdr = "evaera/cmdr@1.8.4"